name: memory_minder_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #sub module
  local_storage:
    path: ./modules/local_storage
  network:
    path: ./modules/network

  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  flutter_custom_logger: ^1.0.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/svg/
    - lib/assets/images/svg/
    - lib/assets/images/other/
    - lib/i18n/langs/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/roboto/Roboto-Black.ttf
        - asset: lib/assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Bold.ttf
        - asset: lib/assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Italic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Light.ttf
        - asset: lib/assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Medium.ttf
        - asset: lib/assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Regular.ttf
        - asset: lib/assets/fonts/roboto/Roboto-ThinItalic.ttf
