name: memory_minder_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #sub module
  local_storage:
    path: ./modules/local_storage
  network:
    path: ./modules/network
  models:
    path: ./modules/models

  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/svg/
    - lib/assets/images/svg/
    - lib/assets/images/other/
    - lib/i18n/langs/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/roboto/Roboto-Black.ttf
        - asset: lib/assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Bold.ttf
        - asset: lib/assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Italic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Light.ttf
        - asset: lib/assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Medium.ttf
        - asset: lib/assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: lib/assets/fonts/roboto/Roboto-Regular.ttf
        - asset: lib/assets/fonts/roboto/Roboto-ThinItalic.ttf
