name: memory_minder_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  flutter_custom_logger: ^1.0.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  flutter_flavorizr: ^2.2.3
  google_fonts: ^6.2.1

flavorizr:
  flavors:
    production:
      app:
        name: "Memory Minder"
      android:
        applicationId: "com.example.memory_minder_app"
        firebase:
          config: "./env/firebase/production/google-services.json"
      ios:
        bundleId: "com.example.memoryMinderApp"
        firebase:
          config: "./env/firebase/production/GoogleService-Info.plist"

    dev:
      app:
        name: "Memory Minder Dev"
      android:
        applicationId: "com.example.memory_minder_app.dev"
        firebase:
          config: "./env/firebase/dev/google-services.json"
      ios:
        bundleId: "com.example.memoryMinderApp.dev"
        firebase:
          config: "./env/firebase/dev/GoogleService-Info.plist"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/svg/
    - lib/assets/icons/other/
    - lib/assets/images/svg/
    - lib/assets/images/other/
    - lib/i18n/langs/
    - lib/assets/google_fonts/
